// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-XHHwCFqtvlE54p6tpbsFuXEliQtTRhY',
    appId: '1:37834273743:web:38ecf596be5c71457bd8ba',
    messagingSenderId: '37834273743',
    projectId: 'doctorappdatabase',
    authDomain: 'doctorappdatabase.firebaseapp.com',
    databaseURL: 'https://doctorappdatabase-default-rtdb.firebaseio.com',
    storageBucket: 'doctorappdatabase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJc5AXkNjgrWtVrBaKQzYmg1CGPwbphzk',
    appId: '1:37834273743:android:2ad75012254401b67bd8ba',
    messagingSenderId: '37834273743',
    projectId: 'doctorappdatabase',
    databaseURL: 'https://doctorappdatabase-default-rtdb.firebaseio.com',
    storageBucket: 'doctorappdatabase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt7nmsry5DBxkBpKo3WnY5PG4PLfdjagE',
    appId: '1:37834273743:ios:1e2ef98febedd5247bd8ba',
    messagingSenderId: '37834273743',
    projectId: 'doctorappdatabase',
    databaseURL: 'https://doctorappdatabase-default-rtdb.firebaseio.com',
    storageBucket: 'doctorappdatabase.appspot.com',
    iosBundleId: 'com.example.doctorapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCt7nmsry5DBxkBpKo3WnY5PG4PLfdjagE',
    appId: '1:37834273743:ios:1e2ef98febedd5247bd8ba',
    messagingSenderId: '37834273743',
    projectId: 'doctorappdatabase',
    databaseURL: 'https://doctorappdatabase-default-rtdb.firebaseio.com',
    storageBucket: 'doctorappdatabase.appspot.com',
    iosBundleId: 'com.example.doctorapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-XHHwCFqtvlE54p6tpbsFuXEliQtTRhY',
    appId: '1:37834273743:web:7129e4347b8a289a7bd8ba',
    messagingSenderId: '37834273743',
    projectId: 'doctorappdatabase',
    authDomain: 'doctorappdatabase.firebaseapp.com',
    databaseURL: 'https://doctorappdatabase-default-rtdb.firebaseio.com',
    storageBucket: 'doctorappdatabase.appspot.com',
  );

}